apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.name" . }}
  labels:
    app: {{ include "core.name" . }}
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "core.name" . }}
