apiVersion: v1
kind: ServiceAccount
metadata:
  name: tkeel-manager
  namespace: keel-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tkeel-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tkeel-manager
    namespace: keel-system