// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var errUnknown *errors.TError
var errInvalidArgument *errors.TError
var errPluginList *errors.TError

func init() {
	errUnknown = errors.New(int(codes.Unknown), "io.tkeel.rudder.api.profile.v1.ERR_UNKNOWN", "未知错误")
	errors.Register(errUnknown)
	errInvalidArgument = errors.New(int(codes.InvalidArgument), "io.tkeel.rudder.api.profile.v1.ERR_INVALID_ARGUMENT", "参数错误")
	errors.Register(errInvalidArgument)
	errPluginList = errors.New(int(codes.Unknown), "io.tkeel.rudder.api.profile.v1.ERR_PLUGIN_LIST", "获取插件列表错误")
	errors.Register(errPluginList)
}

func ErrUnknown() errors.Error {
	return errUnknown
}

func ErrInvalidArgument() errors.Error {
	return errInvalidArgument
}

func ErrPluginList() errors.Error {
	return errPluginList
}
