// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileClient interface {
	GetTenantProfile(ctx context.Context, in *GetTenantProfileRequest, opts ...grpc.CallOption) (*GetTenantProfileResponse, error)
	SetTenantPluginProfile(ctx context.Context, in *SetTenantPluginProfileRequest, opts ...grpc.CallOption) (*SetTenantPluginProfileResponse, error)
}

type profileClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileClient(cc grpc.ClientConnInterface) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) GetTenantProfile(ctx context.Context, in *GetTenantProfileRequest, opts ...grpc.CallOption) (*GetTenantProfileResponse, error) {
	out := new(GetTenantProfileResponse)
	err := c.cc.Invoke(ctx, "/io.tkeel.rudder.api.profile.v1.Profile/GetTenantProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileClient) SetTenantPluginProfile(ctx context.Context, in *SetTenantPluginProfileRequest, opts ...grpc.CallOption) (*SetTenantPluginProfileResponse, error) {
	out := new(SetTenantPluginProfileResponse)
	err := c.cc.Invoke(ctx, "/io.tkeel.rudder.api.profile.v1.Profile/SetTenantPluginProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
// All implementations must embed UnimplementedProfileServer
// for forward compatibility
type ProfileServer interface {
	GetTenantProfile(context.Context, *GetTenantProfileRequest) (*GetTenantProfileResponse, error)
	SetTenantPluginProfile(context.Context, *SetTenantPluginProfileRequest) (*SetTenantPluginProfileResponse, error)
	mustEmbedUnimplementedProfileServer()
}

// UnimplementedProfileServer must be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (UnimplementedProfileServer) GetTenantProfile(context.Context, *GetTenantProfileRequest) (*GetTenantProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantProfile not implemented")
}
func (UnimplementedProfileServer) SetTenantPluginProfile(context.Context, *SetTenantPluginProfileRequest) (*SetTenantPluginProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTenantPluginProfile not implemented")
}
func (UnimplementedProfileServer) mustEmbedUnimplementedProfileServer() {}

// UnsafeProfileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServer will
// result in compilation errors.
type UnsafeProfileServer interface {
	mustEmbedUnimplementedProfileServer()
}

func RegisterProfileServer(s grpc.ServiceRegistrar, srv ProfileServer) {
	s.RegisterService(&Profile_ServiceDesc, srv)
}

func _Profile_GetTenantProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).GetTenantProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.tkeel.rudder.api.profile.v1.Profile/GetTenantProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).GetTenantProfile(ctx, req.(*GetTenantProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profile_SetTenantPluginProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTenantPluginProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).SetTenantPluginProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.tkeel.rudder.api.profile.v1.Profile/SetTenantPluginProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).SetTenantPluginProfile(ctx, req.(*SetTenantPluginProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Profile_ServiceDesc is the grpc.ServiceDesc for Profile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.tkeel.rudder.api.profile.v1.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTenantProfile",
			Handler:    _Profile_GetTenantProfile_Handler,
		},
		{
			MethodName: "SetTenantPluginProfile",
			Handler:    _Profile_SetTenantPluginProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/profile/v1/plgprofile.proto",
}
