package kustomize

const (
	daprEnabledKey                 = "dapr.io/enabled"
	daprAppPortKey                 = "dapr.io/app-port"
	daprConfigKey                  = "dapr.io/config"
	daprAppProtocolKey             = "dapr.io/app-protocol"
	appIDKey                       = "dapr.io/app-id"
	daprEnableProfilingKey         = "dapr.io/enable-profiling"
	daprLogLevel                   = "dapr.io/log-level"
	daprAPITokenSecret             = "dapr.io/api-token-secret" /* #nosec */
	daprAppTokenSecret             = "dapr.io/app-token-secret" /* #nosec */
	daprLogAsJSON                  = "dapr.io/log-as-json"
	daprAppMaxConcurrencyKey       = "dapr.io/app-max-concurrency"
	daprEnableMetricsKey           = "dapr.io/enable-metrics"
	daprMetricsPortKey             = "dapr.io/metrics-port"
	daprEnableDebugKey             = "dapr.io/enable-debug"
	daprDebugPortKey               = "dapr.io/debug-port"
	daprEnvKey                     = "dapr.io/env"
	daprCPULimitKey                = "dapr.io/sidecar-cpu-limit"
	daprMemoryLimitKey             = "dapr.io/sidecar-memory-limit"
	daprCPURequestKey              = "dapr.io/sidecar-cpu-request"
	daprMemoryRequestKey           = "dapr.io/sidecar-memory-request"
	daprListenAddresses            = "dapr.io/sidecar-listen-addresses"
	daprLivenessProbeDelayKey      = "dapr.io/sidecar-liveness-probe-delay-seconds"
	daprLivenessProbeTimeoutKey    = "dapr.io/sidecar-liveness-probe-timeout-seconds"
	daprLivenessProbePeriodKey     = "dapr.io/sidecar-liveness-probe-period-seconds"
	daprLivenessProbeThresholdKey  = "dapr.io/sidecar-liveness-probe-threshold"
	daprReadinessProbeDelayKey     = "dapr.io/sidecar-readiness-probe-delay-seconds"
	daprReadinessProbeTimeoutKey   = "dapr.io/sidecar-readiness-probe-timeout-seconds"
	daprReadinessProbePeriodKey    = "dapr.io/sidecar-readiness-probe-period-seconds"
	daprReadinessProbeThresholdKey = "dapr.io/sidecar-readiness-probe-threshold"
	daprImage                      = "dapr.io/sidecar-image"
	daprAppSSLKey                  = "dapr.io/app-ssl"
	daprMaxRequestBodySize         = "dapr.io/http-max-request-size"
	daprReadBufferSize             = "dapr.io/http-read-buffer-size"
	daprHTTPStreamRequestBody      = "dapr.io/http-stream-request-body"
)
