name: Feature Request
description: File a feature request
title: "[FEAT_REQUEST]: "
labels: ["feat", "fr", "feat_request"]
assignees:
  - liuzhen21
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your key comments
  - type: textarea
    id: what-except
    attributes:
      label: What Is Your Expect
      description: We would love to know what you need
      placeholder: Tell us what you want!
      value: "Maybe ..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [core](https://github.com/tkeel-io/core)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false