// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var errUnknown *errors.TError
var errSecretNotMatch *errors.TError
var errClientIdAlreadyExists *errors.TError
var errInvaildPluginId *errors.TError
var errInternalStore *errors.TError

func init() {
	errUnknown = errors.New(int(codes.Unknown), "oauth2.v1.ERR_UNKNOWN", Error_ERR_UNKNOWN.String())
	errors.Register(errUnknown)
	errSecretNotMatch = errors.New(int(codes.InvalidArgument), "oauth2.v1.ERR_SECRET_NOT_MATCH", Error_ERR_SECRET_NOT_MATCH.String())
	errors.Register(errSecretNotMatch)
	errClientIdAlreadyExists = errors.New(int(codes.AlreadyExists), "oauth2.v1.ERR_CLIENT_ID_ALREADY_EXISTS", Error_ERR_CLIENT_ID_ALREADY_EXISTS.String())
	errors.Register(errClientIdAlreadyExists)
	errInvaildPluginId = errors.New(int(codes.InvalidArgument), "oauth2.v1.ERR_INVAILD_PLUGIN_ID", Error_ERR_INVAILD_PLUGIN_ID.String())
	errors.Register(errInvaildPluginId)
	errInternalStore = errors.New(int(codes.Internal), "oauth2.v1.ERR_INTERNAL_STORE", Error_ERR_INTERNAL_STORE.String())
	errors.Register(errInternalStore)
}

func ErrUnknown() errors.Error {
	return errUnknown
}

func ErrSecretNotMatch() errors.Error {
	return errSecretNotMatch
}

func ErrClientIdAlreadyExists() errors.Error {
	return errClientIdAlreadyExists
}

func ErrInvaildPluginId() errors.Error {
	return errInvaildPluginId
}

func ErrInternalStore() errors.Error {
	return errInternalStore
}
