// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var errUnknown *errors.TError
var errInvalidArgument *errors.TError
var errUnauthenticated *errors.TError
var errInternalError *errors.TError
var errUpstreamNotEnable *errors.TError
var errNoPermission *errors.TError
var errInvalidXPluginJwtToken *errors.TError
var errInvalidXTkeelAuthToken *errors.TError
var errUpstreamNotFound *errors.TError

func init() {
	errUnknown = errors.New(int(codes.Unknown), "io.tkeel.security.api.authentication.v1.ERR_UNKNOWN", "未知类型")
	errors.Register(errUnknown)
	errInvalidArgument = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.authentication.v1.ERR_INVALID_ARGUMENT", "请求参数无效")
	errors.Register(errInvalidArgument)
	errUnauthenticated = errors.New(int(codes.Unauthenticated), "io.tkeel.security.api.authentication.v1.ERR_UNAUTHENTICATED", "认证错误")
	errors.Register(errUnauthenticated)
	errInternalError = errors.New(int(codes.Internal), "io.tkeel.security.api.authentication.v1.ERR_INTERNAL_ERROR", "内部错误")
	errors.Register(errInternalError)
	errUpstreamNotEnable = errors.New(int(codes.PermissionDenied), "io.tkeel.security.api.authentication.v1.ERR_UPSTREAM_NOT_ENABLE", "上游插件未启用")
	errors.Register(errUpstreamNotEnable)
	errNoPermission = errors.New(int(codes.PermissionDenied), "io.tkeel.security.api.authentication.v1.ERR_NO_PERMISSION", "无权限")
	errors.Register(errNoPermission)
	errInvalidXPluginJwtToken = errors.New(int(codes.Unauthenticated), "io.tkeel.security.api.authentication.v1.ERR_INVALID_X_PLUGIN_JWT_TOKEN", "无效的x-plugin-jwttoken")
	errors.Register(errInvalidXPluginJwtToken)
	errInvalidXTkeelAuthToken = errors.New(int(codes.Unauthenticated), "io.tkeel.security.api.authentication.v1.ERR_INVALID_X_TKEEL_AUTH_TOKEN", "无效的x-tKeel-authtoken")
	errors.Register(errInvalidXTkeelAuthToken)
	errUpstreamNotFound = errors.New(int(codes.NotFound), "io.tkeel.security.api.authentication.v1.ERR_UPSTREAM_NOT_FOUND", "上游插件未找到")
	errors.Register(errUpstreamNotFound)
}

func ErrUnknown() errors.Error {
	return errUnknown
}

func ErrInvalidArgument() errors.Error {
	return errInvalidArgument
}

func ErrUnauthenticated() errors.Error {
	return errUnauthenticated
}

func ErrInternalError() errors.Error {
	return errInternalError
}

func ErrUpstreamNotEnable() errors.Error {
	return errUpstreamNotEnable
}

func ErrNoPermission() errors.Error {
	return errNoPermission
}

func ErrInvalidXPluginJwtToken() errors.Error {
	return errInvalidXPluginJwtToken
}

func ErrInvalidXTkeelAuthToken() errors.Error {
	return errInvalidXTkeelAuthToken
}

func ErrUpstreamNotFound() errors.Error {
	return errUpstreamNotFound
}
