// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var configErrUnknown *errors.TError
var configErrInternalError *errors.TError

func init() {
	configErrUnknown = errors.New(int(codes.Unknown), "io.tkeel.rudder.api.config.v1.CONFIG_ERR_UNKNOWN", "未知类型")
	errors.Register(configErrUnknown)
	configErrInternalError = errors.New(int(codes.Internal), "io.tkeel.rudder.api.config.v1.CONFIG_ERR_INTERNAL_ERROR", "请求后端内部错误")
	errors.Register(configErrInternalError)
}

func ConfigErrUnknown() errors.Error {
	return configErrUnknown
}

func ConfigErrInternalError() errors.Error {
	return configErrInternalError
}
