// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var entryErrUnknown *errors.TError
var entryErrInvalidTenant *errors.TError
var entryErrInternalError *errors.TError

func init() {
	entryErrUnknown = errors.New(int(codes.Unknown), "io.tkeel.rudder.api.entry.v1.ENTRY_ERR_UNKNOWN", "未知类型")
	errors.Register(entryErrUnknown)
	entryErrInvalidTenant = errors.New(int(codes.InvalidArgument), "io.tkeel.rudder.api.entry.v1.ENTRY_ERR_INVALID_TENANT", "无效的租户ID")
	errors.Register(entryErrInvalidTenant)
	entryErrInternalError = errors.New(int(codes.Internal), "io.tkeel.rudder.api.entry.v1.ENTRY_ERR_INTERNAL_ERROR", "请求后端内部错误")
	errors.Register(entryErrInternalError)
}

func EntryErrUnknown() errors.Error {
	return entryErrUnknown
}

func EntryErrInvalidTenant() errors.Error {
	return entryErrInvalidTenant
}

func EntryErrInternalError() errors.Error {
	return entryErrInternalError
}
