// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var entryErrUnknown *errors.TError
var entryErrInvaildTenant *errors.TError
var entryErrInternalError *errors.TError

func init() {
	entryErrUnknown = errors.New(int(codes.Unknown), "entry.v1.ENTRY_ERR_UNKNOWN", Error_ENTRY_ERR_UNKNOWN.String())
	errors.Register(entryErrUnknown)
	entryErrInvaildTenant = errors.New(int(codes.InvalidArgument), "entry.v1.ENTRY_ERR_INVAILD_TENANT", Error_ENTRY_ERR_INVAILD_TENANT.String())
	errors.Register(entryErrInvaildTenant)
	entryErrInternalError = errors.New(int(codes.Internal), "entry.v1.ENTRY_ERR_INTERNAL_ERROR", Error_ENTRY_ERR_INTERNAL_ERROR.String())
	errors.Register(entryErrInternalError)
}

func EntryErrUnknown() errors.Error {
	return entryErrUnknown
}

func EntryErrInvaildTenant() errors.Error {
	return entryErrInvaildTenant
}

func EntryErrInternalError() errors.Error {
	return entryErrInternalError
}
