// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	errors "github.com/tkeel-io/kit/errors"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the ego package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

var oauthErrUnknown *errors.TError
var oauthErrInvalidRequest *errors.TError
var oauthErrUnauthorizedClient *errors.TError
var oauthErrAccessDenied *errors.TError
var oauthErrUnsupportedResponseType *errors.TError
var oauthErrInvalidScope *errors.TError
var oauthErrServerError *errors.TError
var oauthErrInvalidClient *errors.TError
var oauthErrInvalidGrant *errors.TError
var oauthErrUnsupportedGrantType *errors.TError
var oauthErrInvalidAccessToken *errors.TError
var oauthErrInvalidResetPwd *errors.TError

func init() {
	oauthErrUnknown = errors.New(int(codes.Unknown), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_UNKNOWN", "未知类型")
	errors.Register(oauthErrUnknown)
	oauthErrInvalidRequest = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_REQUEST", "无效请求")
	errors.Register(oauthErrInvalidRequest)
	oauthErrUnauthorizedClient = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_UNAUTHORIZED_CLIENT", "未授权")
	errors.Register(oauthErrUnauthorizedClient)
	oauthErrAccessDenied = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_ACCESS_DENIED", "限制访问")
	errors.Register(oauthErrAccessDenied)
	oauthErrUnsupportedResponseType = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_UNSUPPORTED_RESPONSE_TYPE", "不支持的授权返回类型")
	errors.Register(oauthErrUnsupportedResponseType)
	oauthErrInvalidScope = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_SCOPE", "无效范围")
	errors.Register(oauthErrInvalidScope)
	oauthErrServerError = errors.New(int(codes.Internal), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_SERVER_ERROR", "服务错误")
	errors.Register(oauthErrServerError)
	oauthErrInvalidClient = errors.New(int(codes.PermissionDenied), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_CLIENT", "无效客户端")
	errors.Register(oauthErrInvalidClient)
	oauthErrInvalidGrant = errors.New(int(codes.Internal), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_GRANT", "无效授权")
	errors.Register(oauthErrInvalidGrant)
	oauthErrUnsupportedGrantType = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_UNSUPPORTED_GRANT_TYPE", "不支持的授予类型")
	errors.Register(oauthErrUnsupportedGrantType)
	oauthErrInvalidAccessToken = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_ACCESS_TOKEN", "不支持的授予类型")
	errors.Register(oauthErrInvalidAccessToken)
	oauthErrInvalidResetPwd = errors.New(int(codes.InvalidArgument), "io.tkeel.security.api.oauth.v1.OAUTH_ERR_INVALID_RESET_PWD", "重置密码链接无效")
	errors.Register(oauthErrInvalidResetPwd)
}

func OauthErrUnknown() errors.Error {
	return oauthErrUnknown
}

func OauthErrInvalidRequest() errors.Error {
	return oauthErrInvalidRequest
}

func OauthErrUnauthorizedClient() errors.Error {
	return oauthErrUnauthorizedClient
}

func OauthErrAccessDenied() errors.Error {
	return oauthErrAccessDenied
}

func OauthErrUnsupportedResponseType() errors.Error {
	return oauthErrUnsupportedResponseType
}

func OauthErrInvalidScope() errors.Error {
	return oauthErrInvalidScope
}

func OauthErrServerError() errors.Error {
	return oauthErrServerError
}

func OauthErrInvalidClient() errors.Error {
	return oauthErrInvalidClient
}

func OauthErrInvalidGrant() errors.Error {
	return oauthErrInvalidGrant
}

func OauthErrUnsupportedGrantType() errors.Error {
	return oauthErrUnsupportedGrantType
}

func OauthErrInvalidAccessToken() errors.Error {
	return oauthErrInvalidAccessToken
}

func OauthErrInvalidResetPwd() errors.Error {
	return oauthErrInvalidResetPwd
}
