apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keel.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "keel.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "keel.name" . }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ include "keel.name" . }}
        dapr.io/app-port: {{ .Values.httpPort | quote }}
        dapr.io/config: {{ .Values.daprConfig }}
      labels:
        app: {{ include "keel.name" . }}
    spec:
      {{- if .imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ include "keel.name" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.httpPort }}
          env:
            - name: TKEEL_DEBUG
              value: {{ .Values.debug |quote }}
            - name: TKEEL_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: TKEEL_HTTP_ADDR
              value: {{ printf ":%v" .Values.httpPort }}
            - name: TKEEL_GRPC_ADDR
              value: {{ printf ":%v" .Values.grpcPort }}
            - name: TKEEL_DAPR_PUBLIC_STATE_NAME
              value: {{ printf "%s-redis-public-store" .Values.middleware.name }}
            - name: TKEEL_WATCH_INTERVAL
              value: {{ .Values.watchInterval }}
            {{- if .Values.tkeelVersion }}
            - name: TKEEL_VERSION
              value: {{ .Values.tkeelVersion }}
            {{- end }}
            - name: TKEEL_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name